const stocks = [
  {
    name:"ASX:BHP",
    symbolsCode:"BHP.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:FMG",
    symbolsCode:"FMG.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:RIO",
    symbolsCode:"RIO.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:NCM",
    symbolsCode:"NCM.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:S32",
    symbolsCode:"S32.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:PLS",
    symbolsCode:"PLS.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:NST",
    symbolsCode:"NST.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:MIN",
    symbolsCode:"MIN.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:IGO",
    symbolsCode:"IGO.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:AKE",
    symbolsCode:"AKE.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:BSL",
    symbolsCode:"BSL.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:LYC",
    symbolsCode:"LYC.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:EVN",
    symbolsCode:"EVN.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:LTR",
    symbolsCode:"LTR.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:ILU",
    symbolsCode:"ILU.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:AWC",
    symbolsCode:"AWC.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:CIA",
    symbolsCode:"CIA.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:SGM",
    symbolsCode:"SGM.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:AVZ",
    symbolsCode:"AVZ.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:SFR",
    symbolsCode:"SFR.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:ZIM",
    symbolsCode:"ZIM.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:NIC",
    symbolsCode:"NIC.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:CRN",
    symbolsCode:"CRN.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:DRR",
    symbolsCode:"DRR.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:DEG",
    symbolsCode:"DEG.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:PRU",
    symbolsCode:"PRU.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:CHN",
    symbolsCode:"CHN.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:SMR",
    symbolsCode:"SMR.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:SYA",
    symbolsCode:"SYA.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:CXO",
    symbolsCode:"CXO.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:BGL",
    symbolsCode:"BGL.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:CMM",
    symbolsCode:"CMM.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:GOR",
    symbolsCode:"GOR.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:RRL",
    symbolsCode:"RRL.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:EMR",
    symbolsCode:"EMR.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:RMS",
    symbolsCode:"RMS.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:GMD",
    symbolsCode:"GMD.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:LLL",
    symbolsCode:"LLL.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:VSL",
    symbolsCode:"VSL.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:SLR",
    symbolsCode:"SLR.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:IMD",
    symbolsCode:"IMD.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:LRS",
    symbolsCode:"LRS.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:WAF",
    symbolsCode:"WAF.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:RSG",
    symbolsCode:"RSG.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:ADT",
    symbolsCode:"ADT.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:WGX",
    symbolsCode:"WGX.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:PRN",
    symbolsCode:"PRN.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:MCR",
    symbolsCode:"MCR.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:VUL",
    symbolsCode:"VUL.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:RED",
    symbolsCode:"RED.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
];

module.exports = stocks;
